"""**Whether the names at module level are the same kind of thing torch has.**

`borch/__init__.py` puts Tensor's methods out as module functions too — torch offers both
`x.sum()` and `torch.sum(x)`, and a list written by hand loses one the next time a method is
added, so it is generated by a loop.

That loop **took names that are not functions in torch.** With a function sitting on our
side, code using the name for its real purpose stops **one step further along:**

    zeros(2, dtype=torch.float)   →  'function' object has no attribute 'np'

which says a function is standing where a type should be, and that wording is
indistinguishable from a typo. Eight types (`float`, `double`, `int`, `bool`, `half`,
`short`, `bfloat16`, `chalf`) were caught that way and **taken out by hand across three
goes.** While it is done by hand there is no rule, so a fourth is coming.

## The two things this check asks

- **Is it not short** — anything the loop generated that is not a function in torch turns
  this red. The day a new method covers such a name, it is caught.
- **Is it not stale** — whether the names written into `_NOT_OURS` really are non-functions
  in torch. If torch makes one a function, our reason for excluding it is gone.

The core does not lean on torch, so the table is written in the source and **the comparison
happens here.** The same shape as this repository's `KNOWN_ABSENT` and `NOT_PORTED` — there
is a list, and it cries when the list drifts.
"""

import inspect
import types

import torch

import borch

LOOP_MADE = "_as_function.<locals>.call"


def _torch_kind(name):
    """What that name is in torch. None (which is fine) if it is a function."""
    value = getattr(torch, name)
    if isinstance(value, torch.dtype):
        return "dtype"
    if isinstance(value, types.ModuleType):
        return "a namespace"
    if inspect.isclass(value):
        return "a class"
    if not callable(value):
        return type(value).__name__
    return None


def test_the_loop_does_not_claim_a_name_torch_gives_as_something_else():
    """A name the loop generated has to be **a function** in torch too."""
    stolen = []
    for name in sorted(dir(borch)):
        if name.startswith("_") or not hasattr(torch, name):
            continue
        if getattr(getattr(borch, name), "__qualname__", "") != LOOP_MADE:
            continue
        kind = _torch_kind(name)
        if kind is not None:
            stolen.append(f"borch.{name} — in torch it is {kind}")
    assert not stolen, (
        "functions generated from methods are covering **something of another kind in torch**:\n  "
        + "\n  ".join(stolen) + "\n\n"
        "Write it into `_NOT_OURS` in `borch/__init__.py` with a reason, or if the name is a\n"
        "type, put the real type **above** the loop. With a function sitting there, the error\n"
        "lands one step further along."
    )


def test_the_not_ours_table_does_not_rot():
    """Whether an excluded name really is not a function in torch."""
    stale = []
    for name, why in sorted(borch._NOT_OURS.items()):
        if not hasattr(torch, name):
            stale.append(f"{name} — torch does not have that name ({why})")
        elif _torch_kind(name) is None:
            stale.append(f"{name} — it is a function in torch now ({why})")
    assert not stale, (
        "`_NOT_OURS` is stale:\n  " + "\n  ".join(stale) + "\n\n"
        "Delete those rows — a list whose reason is gone reads to the next person as grounds."
    )
